# Generated by Django 3.2.8 on 2021-11-30 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silkapp', '0002_product_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug_name',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
