# Generated by Django 3.2.8 on 2021-11-30 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('silkapp', '0003_category_slug_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='slug_name',
            new_name='slug',
        ),
    ]
