# Generated by Django 3.2.8 on 2021-12-17 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silkapp', '0006_subcategory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
