# Generated by Django 3.2.8 on 2021-12-17 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silkapp', '0008_auto_20211217_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=models.TextField(max_length=600),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(upload_to='photos/%Y/%m/%d'),
        ),
    ]
