# Generated by Django 3.2.8 on 2022-01-28 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silkapp', '0011_alter_product_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentNRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('rate', models.DecimalField(decimal_places=0, default=0, max_digits=1)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='photos/%Y/%m/%d')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='img',
        ),
        migrations.AddField(
            model_name='product',
            name='comments',
            field=models.ManyToManyField(to='silkapp.CommentNRate'),
        ),
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ManyToManyField(to='silkapp.ProductImage'),
        ),
    ]
