# Generated by Django 3.2.8 on 2022-01-28 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('silkapp', '0012_auto_20220128_1714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='comments',
            new_name='comment',
        ),
    ]
