# Generated by Django 3.2.8 on 2022-01-29 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silkapp', '0013_rename_comments_product_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentnrate',
            name='author',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
