# Generated by Django 3.2.8 on 2022-02-03 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silkapp', '0014_commentnrate_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
    ]
