# Generated by Django 3.2.8 on 2022-02-03 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silkapp', '0016_multipleimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='multipleimages',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
