# Generated by Django 3.2.8 on 2022-02-07 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('silkapp', '0021_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='bidtype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='silkapp.category'),
            preserve_default=False,
        ),
    ]
