# Generated by Django 3.2.8 on 2022-02-08 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silkapp', '0024_chatfriends_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
