# Generated by Django 3.2.8 on 2022-02-08 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silkapp', '0025_chatmessage_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='time',
            field=models.TimeField(),
        ),
    ]
