# Generated by Django 3.2.8 on 2022-02-12 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silkapp', '0027_alter_chatmessage_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='<django.db.models.fields.CharField>', unique=True),
        ),
    ]
