# Generated by Django 3.2.8 on 2022-02-12 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silkapp', '0028_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
