# Generated by Django 3.2.8 on 2022-02-14 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('silkapp', '0029_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='initiator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Initiator+', to='auth.user'),
            preserve_default=False,
        ),
    ]
