# Generated by Django 4.0.4 on 2022-05-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silkapp', '0032_alter_product_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
