# Generated by Django 4.0.4 on 2022-05-18 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silkapp', '0033_alter_catalog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
